# Generated by Django 2.2 on 2020-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(max_length=3000, verbose_name='Description')),
                ('status', models.CharField(default='new', max_length=40, verbose_name='Status')),
                ('execute_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of execution')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
    ]
