# Generated by Django 2.2 on 2020-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200723_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='detail',
            field=models.TextField(default='no description', max_length=3000, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='describe',
            field=models.CharField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In proccess'), ('done', 'Done')], default='new', max_length=40, verbose_name='Status'),
        ),
    ]
