# Generated by Django 2.2 on 2020-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200728_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='execute_at',
            field=models.DateField(blank=True, null=True, verbose_name='Date of execution'),
        ),
    ]
